name: PR checks

on:
  pull_request:

permissions:
  contents: read

jobs:
  common:
    uses: iomete/.github/.github/workflows/common-repository-pr-checks.yml@main
    with:
      runs-on: ubuntu-latest
